"""compact image tables

Revision ID: 02b6191993cc
Revises: 849feba7f470
Create Date: 2025-09-08 11:01:57.129169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "02b6191993cc"
down_revision: Union[str, Sequence[str], None] = "849feba7f470"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_images", "image_width")
    op.drop_column("source_images", "image_height")
    op.drop_column("source_images", "updated_at")
    op.drop_column("target_images", "image_width")
    op.drop_column("target_images", "description")
    op.drop_column("target_images", "image_height")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "target_images",
        sa.Column(
            "image_height", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "target_images",
        sa.Column(
            "description", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "target_images",
        sa.Column(
            "image_width", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "source_images",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "source_images",
        sa.Column(
            "image_height", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "source_images",
        sa.Column(
            "image_width", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
