"""add img_path_type column

Revision ID: 635910ae27d2
Revises: 02b6191993cc
Create Date: 2025-09-08 12:00:07.150081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "635910ae27d2"
down_revision: Union[str, Sequence[str], None] = "02b6191993cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_jobs",
        sa.Column(
            "result_file_path_type",
            sa.String(length=50),
            server_default="local",
            nullable=True,
        ),
    )
    op.add_column(
        "source_images",
        sa.Column(
            "file_path_type",
            sa.String(length=50),
            server_default="local",
            nullable=False,
        ),
    )
    op.add_column(
        "target_images",
        sa.Column(
            "file_path_type",
            sa.String(length=50),
            server_default="local",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_images", "file_path_type")
    op.drop_column("source_images", "file_path_type")
    op.drop_column("processing_jobs", "result_file_path_type")
    # ### end Alembic commands ###
