"""modify processed_images table (url_id)

Revision ID: 677792251d35
Revises: 6c18a9ff6208
Create Date: 2025-09-24 17:43:50.354372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677792251d35'
down_revision: Union[str, Sequence[str], None] = '6c18a9ff6208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('url_id', sa.String(length=255), nullable=True))
    op.drop_column('processed_images', 'marked_url_id')
    op.drop_column('processed_images', 'sliced_url_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('sliced_url_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('processed_images', sa.Column('marked_url_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('processed_images', 'url_id')
    # ### end Alembic commands ###
