"""modify processed_images table

Revision ID: 6c18a9ff6208
Revises: 10098555307b
Create Date: 2025-09-24 15:52:19.153211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c18a9ff6208'
down_revision: Union[str, Sequence[str], None] = '10098555307b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('file_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('processed_images_marked_file_hash_key'), 'processed_images', type_='unique')
    op.drop_constraint(op.f('processed_images_sliced_file_hash_key'), 'processed_images', type_='unique')
    op.create_unique_constraint('processed_images_file_hash_key', 'processed_images', ['file_hash'])
    op.drop_column('processed_images', 'sliced_file_hash')
    op.drop_column('processed_images', 'marked_file_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_images', sa.Column('marked_file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('processed_images', sa.Column('sliced_file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint('processed_images_file_hash_key', 'processed_images', type_='unique')
    op.create_unique_constraint(op.f('processed_images_sliced_file_hash_key'), 'processed_images', ['sliced_file_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('processed_images_marked_file_hash_key'), 'processed_images', ['marked_file_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('processed_images', 'file_hash')
    # ### end Alembic commands ###
