"""modify target_images

Revision ID: 849feba7f470
Revises: f65842c8205c
Create Date: 2025-09-08 07:08:59.504689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "849feba7f470"
down_revision: Union[str, Sequence[str], None] = "f65842c8205c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_target_images_category"), table_name="target_images"
    )
    op.drop_column("target_images", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "target_images",
        sa.Column(
            "category",
            sa.VARCHAR(length=50),
            server_default=sa.text("'general'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("idx_target_images_category"),
        "target_images",
        ["category"],
        unique=False,
    )
    # ### end Alembic commands ###
