"""create processed_image table

Revision ID: dc86721534dc
Revises: e674fc3ef3f3
Create Date: 2025-09-21 04:59:11.365990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc86721534dc'
down_revision: Union[str, Sequence[str], None] = 'e674fc3ef3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_image',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), nullable=False),
    sa.Column('marked_file_path', sa.String(length=500), nullable=False),
    sa.Column('marked_file_type', sa.String(length=10), server_default=sa.text("'local'::character varying"), nullable=False),
    sa.Column('marked_file_hash', sa.String(length=64), nullable=False),
    sa.Column('sliced_file_path', sa.String(length=500), nullable=False),
    sa.Column('sliced_file_type', sa.String(length=10), server_default=sa.text("'local'::character varying"), nullable=False),
    sa.Column('sliced_file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('marked_file_size', sa.Integer(), nullable=True),
    sa.Column('marked_file_mime_type', sa.String(length=50), nullable=True),
    sa.Column('marked_url_id', sa.String(length=255), nullable=True),
    sa.Column('sliced_file_size', sa.Integer(), nullable=True),
    sa.Column('sliced_file_mime_type', sa.String(length=50), nullable=True),
    sa.Column('sliced_url_id', sa.String(length=255), nullable=True),
    sa.CheckConstraint("marked_file_hash::text ~ '^[0-9a-f]{64}$'::text", name='processed_image_marked_file_hash_check'),
    sa.CheckConstraint("marked_file_mime_type::text ~* '^image/'::text", name='processed_image_marked_file_mime_type_check'),
    sa.CheckConstraint("sliced_file_hash::text ~ '^[0-9a-f]{64}$'::text", name='processed_image_sliced_file_hash_check'),
    sa.CheckConstraint("sliced_file_mime_type::text ~* '^image/'::text", name='processed_image_sliced_file_mime_type_check'),
    sa.PrimaryKeyConstraint('id', name='processed_image_pkey'),
    sa.UniqueConstraint('marked_file_hash', name='processed_image_marked_file_hash_key'),
    sa.UniqueConstraint('sliced_file_hash', name='processed_image_sliced_file_hash_key')
    )
    op.create_index('processed_image_created_at_index', 'processed_image', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('processed_image_created_at_index', table_name='processed_image')
    op.drop_table('processed_image')
    # ### end Alembic commands ###
