"""target image - add url id

Revision ID: e3a861af02a0
Revises: 635910ae27d2
Create Date: 2025-09-14 16:01:23.590566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a861af02a0'
down_revision: Union[str, Sequence[str], None] = '635910ae27d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_images', sa.Column('url_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_images', 'url_id')
    # ### end Alembic commands ###
