"""update tags type

Revision ID: e674fc3ef3f3
Revises: e3a861af02a0
Create Date: 2025-09-17 18:43:36.406290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e674fc3ef3f3'
down_revision: Union[str, Sequence[str], None] = 'e3a861af02a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_images', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.drop_index(op.f('idx_source_images_tags'), table_name='source_images')
    op.create_index('idx_source_images_tags_gin', 'source_images', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('target_images', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.drop_index(op.f('idx_target_images_tags'), table_name='target_images')
    op.create_index('idx_target_images_tags_gin', 'target_images', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_target_images_tags_gin', table_name='target_images', postgresql_using='gin')
    op.create_index(op.f('idx_target_images_tags'), 'target_images', ['tags'], unique=False)
    op.alter_column('target_images', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.drop_index('idx_source_images_tags_gin', table_name='source_images', postgresql_using='gin')
    op.create_index(op.f('idx_source_images_tags'), 'source_images', ['tags'], unique=False)
    op.alter_column('source_images', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    # ### end Alembic commands ###
